### ISSUE TITLE
The pop up for the token never comes up

### ISSUE THREAD

**Issue by adelthesuper** [Raguggg/quillbot-premium-for-free#1]
The part where you enter token never comes up for me.

There is also this error:
![image](https://user-images.githubusercontent.com/75554357/214383616-58727d1c-b495-4a36-880d-c08e0d159932.png)
![Capture](https://user-images.githubusercontent.com/75554357/214383723-f1b5f637-a10e-4708-bc8d-b542038faba2.PNG)

**Comment by Raguggg** [comment]
I think you edit the source code so download again and upload it
