### ISSUE TITLE
Failed to load extension

### ISSUE THREAD

**Issue by soumysuwas** [Raguggg/quillbot-premium-for-free#19]
<img width="1440" alt="Screenshot 2024-05-03 at 3 28 58 PM" src="https://github.com/Raguggg/quillbot-premium-for-free/assets/86571607/25b7c4a0-1bc6-4c40-84e5-dcffeb3b4f95">

**Comment by priyanshu312** [comment]
Hi, for resolving this issue, don't put the whole folder in the load unpacked. put the "extension" folder which is there in the main folder, only, into the load unpacked because that folder contains the required manifest file

**Comment by soumysuwas** [comment]
Yes I was able to install but I cannot use the premium features still. Does this extension works only on windows?, I have a macOS device that's why asking.

thanks

**Comment by Ragug** [comment]
it work on all os
