### ISSUE TITLE
Error while clicking "Load Unpacked"

### ISSUE THREAD

**Issue by Ha98Ma** [Raguggg/quillbot-premium-for-free#2]
When clicking "Load Unpacked" the following error shows up. Plz help
"Manifest file is missing or unreadable
Could not load manifest"
<img width="664" alt="Screenshot 2023-06-19 114835" src="https://github.com/Raguggg/quillbot-premium-for-free/assets/137049133/0ea9bf89-7d0b-420d-a522-66ddef0e1b64">

**Comment by TheoZan** [comment]
You need to upload the "extension" folder which is inside the "quillbot-for-free-main" folder.
