### ISSUE TITLE
I get this issue

### ISSUE THREAD

**Issue by Bhumik23gpt** [Raguggg/quillbot-premium-for-free#6]
I get this issue, I reinstalled the extension, still....

<img width="485" alt="image" src="https://github.com/Raguggg/quillbot-premium-for-free/assets/133236838/bfd6793a-23e9-43c0-9b80-2d1edc05aa2c">

**Comment by Raguggg** [comment]
Pls logout your account and re-login it or try with different chrome profiles

**Comment by Bhumik23gpt** [comment]
Tried it multiple times to log in and logout, also changed profiles, Now I have 2 profiles with the same error!

I am not much into technical thing, but I think this can help, when I refresh the page, it shows as this.....

<img width="480" alt="image" src="https://github.com/Raguggg/quillbot-premium-for-free/assets/133236838/0395a885-9a5b-495a-a20e-0c2496286124">
