### ISSUE TITLE
I get this issue #2

### ISSUE THREAD

**Issue by Bhumik23gpt** [Raguggg/quillbot-premium-for-free#7]
Tried it multiple times to log in and logout, also changed profiles, Now I have 2 profiles with the same error!

I am not much into technical thing, but I think this can help, when I refresh the page, it shows as this.....

![image](https://github.com/Raguggg/quillbot-premium-for-free/assets/133236838/41c12cea-db42-4f32-b9d5-3fe8541e5da8)

Also here is screenshot from chrome extensions errors....

![image](https://github.com/Raguggg/quillbot-premium-for-free/assets/133236838/64f404bf-91cd-444c-9c7e-79be6a654e8a)

**Comment by pu9li** [comment]
im also getting the same issue.
waiting for a solution

**Comment by Raguggg** [comment]
It because of chrome update I will fix soon

**Comment by TheBosss0** [comment]
I am getting this same issue again, i just downloaded the extension yesterday.

**Comment by TheBosss0** [comment]
![issue](https://github.com/Raguggg/quillbot-premium-for-free/assets/156002479/afd3a5f8-5f48-419b-bf7d-db04d6837b20)

this is the error its showing in the JS console

**Comment by Pocarai** [comment]
I got the same error in Edge also @Raguggg, Please Fix 🥹

![image](https://github.com/Raguggg/quillbot-premium-for-free/assets/96225118/eca7ffc7-1f36-48cb-984a-a00370bb38cb)

**Comment by Raguggg** [comment]
what version of browser you are using ??

**Comment by Pocarai** [comment]
> what version of browser you are using ??

Microsoft Edge

**Comment by Raguggg** [comment]
if you visit `edge://version` there is show version pls say that

**Comment by Pocarai** [comment]
Here the version
![image](https://github.com/Raguggg/quillbot-premium-for-free/assets/96225118/adc61858-c3dc-4556-865f-149e2665034f)
I always update my Microsoft edge while using it.

**Comment by Raguggg** [comment]
Issue are fixed try latest code [Latest release](https://github.com/Raguggg/quillbot-premium-for-free/releases/tag/v2.1.0)
