### ISSUE TITLE
Quillbot error

### ISSUE THREAD

**Issue by SmittieHP** [Raguggg/quillbot-premium-for-free#8]
![image](https://github.com/Raguggg/quillbot-premium-for-free/assets/157641703/27c85dd6-ba8a-4b82-bfc0-aea5403b4dd8)

After working on Quillbot for a while I  receive this message and it does not rephrase properly
Please help

**Comment by Raguggg** [comment]
Try to use latest version https://github.com/Raguggg/quillbot-premium-for-free/releases/tag/v2.1.0

**Comment by SmittieHP** [comment]
I did download this latest version,but it still gives me that message after a while. I am using Windows 11. Could that be a problem?
