### ISSUE TITLE
paraphrasing tool loops on all premium modes

### ISSUE THREAD

**Issue by Glimehardt** [Raguggg/quillbot-premium-for-free#9]
Was not asked to enter token, but did everything correctly. Initially assumed that Chrome needed to be updated, but that did not solve things either. Is it patched?
![image](https://github.com/Raguggg/quillbot-premium-for-free/assets/158209922/af7279e8-e804-4a5c-bbe5-ecf2571b5fdb)
The premium logo appears to be there. Not code savvy at all, and no error message pops up on the site.

**Comment by adrakchacha** [comment]
hey, 

I'm in the same boat. 

Did you get any fix?

**Comment by Carlliam0518** [comment]
Same! I was wondering if that was a windows 11 problem because when I was at windows 10 it works perfectly fine but now that I updated to windows 11 it suddenly stopped working even when I reinstalled it.

**Comment by 88randan** [comment]
> Same! I was wondering if that was a windows 11 problem because when I was at windows 10 it works perfectly fine but now that I updated to windows 11 it suddenly stopped working even when I reinstalled it.

Same issue on macbook

**Comment by Glimehardt** [comment]
> Same! I was wondering if that was a windows 11 problem because when I was at windows 10 it works perfectly fine but now that I updated to windows 11 it suddenly stopped working even when I reinstalled it.

I'm on Windows 10 and never upgraded - doesn't work

**Comment by p1utoze** [comment]
> Same! I was wondering if that was a windows 11 problem because when I was at windows 10 it works perfectly fine but now that I updated to windows 11 it suddenly stopped working even when I reinstalled it.

Ubuntu User here
I am facing the same issue on chrome browser regardless of the chrome version.

**Comment by Ragug** [comment]
In update code I removed asking token so it not displayed to you.
